[[mgr.prepend_keymap]]
on   = [ "g", "/" ]
run  = "cd /"
desc = "Go to \"/\""

[[mgr.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"
desc = "Diff the selected with the hovered file"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "7" ]
run  = "plugin compress 7z"
desc = "Archive (7z)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "t" ]
run  = "plugin compress tar"
desc = "Archive (tar)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "g" ]
run  = "plugin compress tar.gz"
desc = "Archive (tar + gzip)"
